/*
 * ELE430 Coursework: Producer-Consumer Model
 * Student: Kaung
 * Date: Jan 27, 2026
 *
 * config.h: Compile-time Configuration Parameters
 * * Defines system limits, timing constraints, and validation bounds
 * * used throughout the application.
 */

#ifndef CONFIG_H
#define CONFIG_H

/* --- System Limits ---
 * Hard upper bounds for memory allocation and thread management.
 */
#define MAX_PRODUCERS           10  // Max threads supported by the model
#define MAX_CONSUMERS           5   // Max threads supported by the model
#define MAX_QUEUE_SIZE          20  // Fixed buffer size limit

/* --- Timing Parameters (Seconds) ---
 * Used by random sleep functions to simulate processing time.
 * Values derived from assignment specification.
 */
#define MAX_PRODUCER_WAIT       2   // Max sleep between writes
#define MAX_CONSUMER_WAIT       4   // Max sleep between reads
#define SHUTDOWN_GRACE_PERIOD   5   // Max wait time for thread joining

/* --- Data Generation ---
 * Ranges for the random content generated by producers.
 */
#define DATA_RANGE_MIN          0   
#define DATA_RANGE_MAX          9   
#define PRIORITY_MIN            0   
#define PRIORITY_MAX            9   // 9 is highest priority

/* --- Runtime Validation ---
 * Strict bounds checked against command line arguments in main.c.
 */
#define MIN_PRODUCERS           1   
#define MIN_CONSUMERS           1   
#define MAX_RUNTIME_CONSUMERS   3   // Spec limits runtime consumers to 3 (even if system supports 5)
#define MIN_QUEUE_SIZE          1   
#define MIN_TIMEOUT             1   // Simulation minimum duration

/* --- Debugging --- */
#define DEBUG_MODE              0   // 0 = Normal output (report), 1 = Verbose trace

#endif /* CONFIG_H */